[#55] Specify bug number in "Error: Apply failed: No patch attachments found" message
Not sure we should raise an exception here, but in my case this is
clarifying the output:

```
% yes|git bz apply 41890

📋 Bug 41890 depends on bug 41892 (In Discussion)

📋 Bug 41892 depends on bug 41891 (In Discussion)

📋 Bug 41891 - Move C4::Context->preferences to a separate package

  • 193508 - Bug 41891: Move C4::Context->preference to Koha::Context::Preferences->get

Apply? [(y)es, (n)o, (i)nteractive]
Preparing 1 patch(es):
  ✓ Prepared 1 patch(es)

Applying 1 patch(es):
    ✓ [1/1] Applied Bug 41891: Move C4::Context->preference to Koha::Context::P…

✓ Successfully applied 1 patch(es) from bug 41891

📋 Bug 41892 - Remove C4::Context from C4::Auth's BEGIN block

  • 199285 - Bug 41892: Remove C4::Context from C4::Auth's BEGIN block

Apply? [(y)es, (n)o, (i)nteractive]
Preparing 1 patch(es):
  ✓ Prepared 1 patch(es)

Applying 1 patch(es):
    ✓ [1/1] Applied Bug 41892: Remove C4::Context from C4::Auth's BEGIN block

✓ Successfully applied 1 patch(es) from bug 41892

📋 Bug 41890 depends on bug 41893 (In Discussion)

📋 Bug 41893 - Remove C4::Context from Koha::Plugins's BEGIN block

  • 193507 - Bug 41893: Remove C4::Context from Koha::Plugins's BEGIN block

Apply? [(y)es, (n)o, (i)nteractive]
Preparing 1 patch(es):
  ✓ Prepared 1 patch(es)

Applying 1 patch(es):
    ✓ [1/1] Applied Bug 41893: Remove C4::Context from Koha::Plugins's BEGIN bl…

✓ Successfully applied 1 patch(es) from bug 41893

📋 Bug 41890 depends on bug 41894 (In Discussion)

📋 Bug 41894 - Bareword "C4::Context::only_my_library" not allowed

  • 193513 - Bug 41894: Remove error 'Bareword C4::Context::only_my_library not allowed'

Apply? [(y)es, (n)o, (i)nteractive]
Preparing 1 patch(es):
  ✓ Prepared 1 patch(es)

Applying 1 patch(es):
    ✓ [1/1] Applied Bug 41894: Remove error 'Bareword C4::Context::only_my_libr…

✓ Successfully applied 1 patch(es) from bug 41894

📋 Bug 41890 depends on bug 41896 (Signed Off)

📋 Bug 41896 - Remove C4::Context from Koha::Cache

  • 196218 - Bug 41896: Remove C4::Context from Koha::Cache

Apply? [(y)es, (n)o, (i)nteractive]
Preparing 1 patch(es):
  ✓ Prepared 1 patch(es)

Applying 1 patch(es):
    ✓ [1/1] Applied Bug 41896: Remove C4::Context from Koha::Cache

✓ Successfully applied 1 patch(es) from bug 41896

📋 Bug 41890 depends on bug 41897 (In Discussion)

📋 Bug 41897 depends on bug 41895 (In Discussion)

📋 Bug 41895 - Introduce Koha::Context::UserEnv to reduce circ deps problem

  • 196465 - Bug 41895: Introduce Koha::Context::UserEnv
  • 196466 - Bug 41895: Fix if no userenv defined

Apply? [(y)es, (n)o, (i)nteractive]
Preparing 2 patch(es):
  ✓ Prepared 2 patch(es)

Applying 2 patch(es):
    ✓ [1/2] Applied Bug 41895: Introduce Koha::Context::UserEnv
    ✓ [2/2] Applied Bug 41895: Fix if no userenv defined

✓ Successfully applied 2 patch(es) from bug 41895

📋 Bug 41897 - Remove C4::Context from Koha::Objects::Limit::Library

  • 193512 - Bug 41897: Remove C4::Context from Koha::Objects::Limit::Library
                                                                                                                                                                                                    10:35:17 [3/1623]
Apply? [(y)es, (n)o, (i)nteractive]
Preparing 1 patch(es):
  ✓ Prepared 1 patch(es)

Applying 1 patch(es):
    ✓ [1/1] Applied Bug 41897: Remove C4::Context from Koha::Objects::Limit::Li…

✓ Successfully applied 1 patch(es) from bug 41897

📋 Bug 41890 depends on bug 41974 (In Discussion)

📋 Bug 41974 - Remove C4::Context from Koha::Object

  • 194378 - Bug 41974: Remove C4::Context from Koha::Object

Apply? [(y)es, (n)o, (i)nteractive]
Preparing 1 patch(es):
  ✓ Prepared 1 patch(es)

Applying 1 patch(es):
    ✓ [1/1] Applied Bug 41974: Remove C4::Context from Koha::Object

✓ Successfully applied 1 patch(es) from bug 41974

📋 Bug 41890 depends on bug 41975 (In Discussion)

📋 Bug 41975 depends on bug 41972 (In Discussion)

📋 Bug 41972 - Move C4::Context->interface to Koha::Context::Interface

  • 194379 - Bug 41972: Move C4::Context->interface to Koha::Context::Interface
  • 196213 - Bug 41972: Use memory cache instead of package variable

Apply? [(y)es, (n)o, (i)nteractive]
Preparing 2 patch(es):
  ✓ Prepared 2 patch(es)

Applying 2 patch(es):
    ✓ [1/2] Applied Bug 41972: Move C4::Context->interface to Koha::Context::In…
    ✓ [2/2] Applied Bug 41972: Use memory cache instead of package variable

✓ Successfully applied 2 patch(es) from bug 41972

📋 Bug 41975 - Remove C4::Context from C4::Log

  • 194380 - Bug 41975: Remove C4::Context from C4::Log

Apply? [(y)es, (n)o, (i)nteractive]
Preparing 1 patch(es):
  ✓ Prepared 1 patch(es)

Applying 1 patch(es):
    ✓ [1/1] Applied Bug 41975: Remove C4::Context from C4::Log

✓ Successfully applied 1 patch(es) from bug 41975
Error: Apply failed: No patch attachments found for bug 41890
```